In [72]:
import numpy as numpy
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df = pd.read_csv('train.txt',sep = ';',header = None,names=['text','emotion'])

In [74]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [75]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [76]:
unique_emotion = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotion:
    emotion_numbers[emo]=i
    i+=1
    df['emotion']=df['emotion'].map(emotion_numbers)

In [77]:
df

                                                    text  emotion
0                                i didnt feel humiliated      NaN
1      i can go from feeling so hopeless to so damned...      NaN
2       im grabbing a minute to post i feel greedy wrong      NaN
3      i am ever feeling nostalgic about the fireplac...      NaN
4                                   i am feeling grouchy      NaN
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...      NaN
15996  i am now turning and i feel pathetic that i am...      NaN
15997                     i feel strong and good overall      NaN
15998  i feel like this was such a rude comment and i...      NaN
15999  i know a lot but i feel so stupid because i ca...      NaN

[16000 rows x 2 columns]

In [78]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [79]:
import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [80]:
df_punc = df['text'].apply(remove_punc)
df_punc

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [81]:
def remove_numbers(txt):
    new = ""
    for i in txt: 
        if not i.isdigit(): 
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [82]:
def remove_emojis(txt):
    new = ""
    for i in txt: 
        if i.isascii(): 
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: str

In [83]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\rajpu\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [84]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [85]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\rajpu\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rajpu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [86]:
stop_words = set(stopwords.words('english'))

In [87]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [88]:
def remove(txt): 
    words = word_tokenize(txt)
    cleaned = []
    for i in words: 
        if not i in stop_words: 
            cleaned.append(i)

    return ' '.join(cleaned)

In [89]:
df['text'] = df['text'].apply(remove)

In [90]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [91]:
df

                                                    text  emotion
0                                  didnt feel humiliated      NaN
1      go feeling hopeless damned hopeful around some...      NaN
2              im grabbing minute post feel greedy wrong      NaN
3      ever feeling nostalgic fireplace know still pr...      NaN
4                                        feeling grouchy      NaN
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten      NaN
15996  turning feel pathetic still waiting tables sub...      NaN
15997                           feel strong good overall      NaN
15998                     feel like rude comment im glad      NaN
15999                       know lot feel stupid portray      NaN

[16000 rows x 2 columns]

In [112]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['emotion'] = le.fit_transform(df['emotion'])

In [113]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df['text'], df['emotion'],test_size=0.33,random_state=42)

In [119]:
nb_model.fit(X_train_bow,y)

MultinomialNB()

In [121]:
pred_nb =nb_model.predict(X_test_bow)

ValueError: X has 8407 features, but MultinomialNB is expecting 12285 features as input.